# Generated by Django 5.1 on 2024-08-13 12:30

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
