# Generated by Django 5.1 on 2024-08-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_blog', '0010_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(default='No preview available', max_length=500),
        ),
    ]
