# Generated by Django 5.1 on 2024-08-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_blog', '0015_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
