# Generated by Django 5.1 on 2024-08-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_blog', '0017_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
